name: Generate UML Diagrams

on:
  push:
    paths:
      - 'include/**'

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install hpp2plantuml
    - name: Run PlantUML Builder
      run:
        python3 .github/scripts/ESP32AlgebraFiltersPlantUmlBuilder.py
    - name: Install PlantUML
      run: sudo apt-get install plantuml
    - name: Generate UML Diagrams
      run: plantuml docs/architecture/classDiagram.puml -tsvg  # Générer l'image .svg
    - name: Check for Diagram Changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add docs/architecture/classDiagram.puml
        git add docs/architecture/classDiagram.svg
        # Vérifie s'il y a des changements
        if git diff --cached --quiet; then
          echo "No changes detected in UML diagram. Skipping commit."
          exit 0
        fi
    - name: Commit UML Diagram
      if: ${{ success() }}  # Exécuter uniquement si des changements sont présents
      run: git commit -m "Updated UML diagram"
    - name: pull before push (with merge if needed)
      run: |
        git config pull.rebase false  # merge
        git pull
    - name: Push changes
      if: ${{ success() }}  # Exécuter uniquement si des changements sont présents
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref_name }}

        
