name: Generate Test Coverage Report

on:
    push:
        paths:
        - 'include/**'
        - 'src/**'
        - 'test/**'

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
            path: |
              ~/.cache/pip
              ~/.platformio/.cache
            key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
            python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Install Specific Compiler
        run: sudo apt-get install -y gcc-11 g++-11

      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Set Compiler Path
        run: |
          export CC=/usr/bin/gcc-11
          export CXX=/usr/bin/g++-11

      - name: Compile with Coverage
        run: |
          platformio test --environment native

      - name: Capture Coverage Data
        run: |
          # Capturer la couverture uniquement pour ESP32AlgebraFilters et linearAlgebra
          lcov --directory . --capture --output-file coverage.info
          # Inclure uniquement les répertoires souhaités
          lcov --extract coverage.info "*include/*" "*src/*" --output-file coverage.info
          # Liste les informations de couverture
          lcov --list coverage.info
          
      - name: Generate HTML Report
        run: |
          rm -rf docs/coverage_report
          mkdir -p docs/coverage_report
          genhtml coverage.info --output-directory docs/coverage_report

      - name: Commit Coverage Report
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add docs/coverage_report/*
          git commit -m "Update coverage report"
          git pull
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}